name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.6
homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/hasura_cache_interceptor
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  uuid: ^3.0.1
  hasura_connect:
    git:
      url: https://github.com/inspireui/hasura_connect.git
      path: packages/hasura_connect
      ref: ae400470c0766cd77a0cdf5448215803aa9b9bb8

dev_dependencies:
  http: ^1.1.0
  mocktail: ^0.3.0 
  test: ^1.20.1
